# Defines stages which are to be executed
stages:
  - API_Build
  - APP_Build
  - test
  - docs
  - clean

# Stage "build"
build:GNU:API:
  stage: API_Build
  tags:
    - CPU, Build
  image: ubuntu:18.04
  script:
    - mkdir build
    - cd build
    - cmake ../  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/OPS-INSTALL -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so
    - make IEEE=1 -j 4
    - make install
  artifacts:
    expire_in: 1 week
    paths:
    - $CI_PROJECT_DIR/OPS-INSTALL

# build:GNU:APP:
#   stage: APP_Build
#   tags:
#     - CPU, Build
#   image: ubuntu:18.04
#   script:
#     - mkdir appbuild
#     - cd appbuild
#     - cmake ../apps/c  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include  -DOPS_INSTALL_DIR=$CI_PROJECT_DIR/OPS-INSTALL -DAPP_INSTALL=$CI_PROJECT_DIR/OPS-APP -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so
#     - make IEEE=1 -j 12
#     - make install
#   dependencies:
#     - build:GNU:API


#Stage "test"
test:GNU:
  stage: test
  tags:
    - GPU,Test
  dependencies:
    - build:GNU:API
  script:
    #- export OPS_INSTALL_PATH=$CI_PROJECT_DIR/OPS-INSTALL
    - mkdir appbuild
    - cd appbuild
    - cmake ../apps/c  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include  -DOPS_INSTALL_DIR=$CI_PROJECT_DIR/OPS-INSTALL -DAPP_INSTALL=$CI_PROJECT_DIR/OPS-APP -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so  -DOPS_APP_TEST=ON  -DGPU_NUMBER=1
    - make IEEE=1 -j 12
    - make test
# Stage "docs"
# run-docs:
#   stage: docs
#   when: always
#   script:
    # - cd doc && make all clean
  # artifacts:
  #   expire_in: 1 week
  #   paths:
  #     - doc/user.pdf
  #     - doc/ops/html
  #     - doc/ops_translator/html