# Defines stages which are to be executed
stages:
  - build
  - test
  - docs
  - clean

# Stage "build"
build:GNU:
  stage: build
  tags:
    - CPU, Build
  image: ubuntu:18.04
  script:
    - mkdir build
    - cd build
    - cmake ../  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include -DCMAKE_INSTALL_PREFIX=$HOME/OPS-INSTALL -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DAPP_INSTALL=$HOME/OPS-APP -DBUILD_OPS_APPS=ON
    - make IEEE=1 -j 12
    - make install
  artifacts:
    expire_in: 1 week
    paths:
    - $HOME/OPS-APP
    - $HOME/OPS-INSTALL


#Stage "test"
gpu_test:GNU:
  stage: test
  tags:
    - GPU,Test
  dependencies:
    - build:GNU
  script:
    - cd OPS-APP/clover_leaf
    - ./clover_leaf_cuda


# Stage "docs"
# run-docs:
#   stage: docs
#   when: always
#   script:
    # - cd doc && make all clean
  # artifacts:
  #   expire_in: 1 week
  #   paths:
  #     - doc/user.pdf
  #     - doc/ops/html
  #     - doc/ops_translator/html