# Defines stages which are to be executed
stages:
  - API_Build
  - APP_Build
  - test
  - docs
  - clean

# Stage "build"
build:GNU:API:
  stage: API_Build
  tags:
    - CPU, Build
  image: ubuntu:18.04
  script:
    - mkdir build
    - cd build
    - cmake ../  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/OPS-INSTALL -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so
    - make IEEE=1 -j 4
    - make install
  artifacts:
    expire_in: 1 week
    paths:
    - $CI_PROJECT_DIR/OPS-INSTALL

build:GNU:APP:
  stage: APP_Build
  tags:
    - CPU, Build
  image: ubuntu:18.04
  script:
    - git clone https://github.com/opensbli/opensbli.git
    - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR/opensbli/
    - ls $CI_PROJECT_DIR/opensbli/
    - ls $CI_PROJECT_DIR/opensbli/OPS
    - |-
      cd $CI_PROJECT_DIR/opensbli/apps
      echo dir=\$1 > translate.sh
      echo pyfile=\$2 >> translate.sh
      echo "cd \$dir" >> translate.sh
      echo "python \$pyfile" >> translate.sh
      echo "head -n-3 opensbli.cpp > tmp.cpp"  >> translate.sh
      echo "echo \"ops_printf(\\\"PASSED\!\\\\\\\\\\\\n\\\");\" >> tmp.cpp " >> translate.sh
      echo "tail -n3 opensbli.cpp >> tmp.cpp" >> translate.sh
      echo "cp tmp.cpp  opensbli.cpp"  >> translate.sh
      echo "rm tmp.cpp" >> translate.sh
      echo "echo \"cmake_minimum_required(VERSION 3.17)\" > CMakeLists.txt" >> translate.sh
      echo "echo \"CreateTempDir()\" >> CMakeLists.txt"  >> translate.sh
      echo "echo \"BUILD_OPS_C_SAMPLE(\$3 \\\"NONE\\\" \\\"NONE\\\" \\\"NONE\\\" \\\"YES\\\")\" >> CMakeLists.txt"  >> translate.sh
      echo "cd \$CI_PROJECT_DIR/opensbli/apps" >> translate.sh
      echo "cp \$dir \$CI_PROJECT_DIR/OPS/apps/c -r" >> translate.sh
      cat translate.sh
      source translate.sh taylor_green_vortex taylor_green_vortex.py tgv
      echo "add_subdirectory(taylor_green_vortex)" >> $CI_PROJECT_DIR/OPS/apps/c/CMakeLists.txt
      source $CI_PROJECT_DIR/translate.sh channel_flow/laminar_2D laminar_channel.py laminar2d
      echo "add_subdirectory(laminar_2D)" >> $CI_PROJECT_DIR/OPS/apps/c/CMakeLists.txt
      cd $CI_PROJECT_DIR/OPS
      ls -l -h $CI_PROJECT_DIR/OPS/apps/c
      cat $CI_PROJECT_DIR/OPS/apps/c/CMakeLists.txt
    - mkdir appbuild
    - cd appbuild
    - cmake ../apps/c  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include  -DOPS_INSTALL_DIR=$CI_PROJECT_DIR/OPS-INSTALL -DAPP_INSTALL=$CI_PROJECT_DIR/OPS-APP -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so
    - make IEEE=1 -j 12
    - make install
  dependencies:
    - build:GNU:API
  except:
    - master

#Stage "test"
test:GNU:
  stage: test
  tags:
    - GPU,Test
  dependencies:
    - build:GNU:API
  script:
    - mkdir appbuild
    - cd appbuild
    - cmake ../apps/c  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include  -DOPS_INSTALL_DIR=$CI_PROJECT_DIR/OPS-INSTALL -DAPP_INSTALL=$CI_PROJECT_DIR/OPS-APP -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so  -DOPS_APP_TEST=ON  -DGPU_NUMBER=1
    - make IEEE=1 -j 12
    - make test
  artifacts:
    expire_in: 1 week
    paths:
    - appbuild/Testing/Temporary
  only:
    - master
#Stage "docs"
make-docs:
  stage: docs
  when: always
  tags:
    - Test
  script:
    - cd doc && make all clean
  artifacts:
    expire_in: 2 week
    paths:
      - doc/user.pdf
      - doc/ops/html
      - doc/ops/latex/refman.pdf
      - doc/ops_translator/html
      - doc/ops_translator/latex/refman.pdf