# Defines stages which are to be executed
stages:
  - API_Build
  - APP_Build
  - test
  - docs
  - clean

# Stage "build"
build:GNU:API:
  stage: API_Build
  tags:
    - CPU, Build
  image: ubuntu:18.04
  script:
    - mkdir build
    - cd build
    - cmake ../  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include -DCMAKE_INSTALL_PREFIX=$CI_BUILDS_DIR/OPS-INSTALL -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so # -DAPP_INSTALL=$HOME/OPS-APP -DBUILD_OPS_APPS=ON
    - make IEEE=1 -j 4
    - make install
  artifacts:
    expire_in: 1 week
    paths:
    - $CI_BUILDS_DIR/OPS-INSTALL

build:GNU:APP:
  stage: APP_Build
  tags:
    - CPU, Build
  image: ubuntu:18.04
  script:
    - ls -l -h
    - cd OPS-INSTALL
    - ls -l -h
    - cd ../
    - mkdir appbuild
    - cd appbuild
    - cmake ../apps/c  -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include  -DOPS_INSTALL_DIR=$CI_BUILDS_DIR/OPS-INSTALL/ -DAPP_INSTALL=$CI_BUILDS_DIR/OPS-APP -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so
    - ls -l -h
    - make IEEE=1 -j 12
    - make install
  artifacts:
    expire_in: 1 week
    paths:
    - $CI_BUILDS_DIR/OPS-APP
  dependencies:
    - build:GNU:API


#Stage "test"
gpu_test:GNU:
  stage: test
  tags:
    - GPU,Test
  dependencies:
    - build:GNU:APP
    - build:GNU:API
  script:
    - cd OPS-APP/clover_leaf
    - ./clover_leaf_cuda


# Stage "docs"
# run-docs:
#   stage: docs
#   when: always
#   script:
    # - cd doc && make all clean
  # artifacts:
  #   expire_in: 1 week
  #   paths:
  #     - doc/user.pdf
  #     - doc/ops/html
  #     - doc/ops_translator/html