# Defines stages which are to be executed
stages:
  - build
  - test
  - docs
  - clean

# Stage "build"
build:GNU:
  stage: build
  image: registry.gitlab.com/op-dsl-ci/ops-ci
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=~/OPS_GNU  -DCMAKE_BUILD_TYPE=Release
    - make
    - make install

build:Clang:
  stage: build
  tags:
    - CPU
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=~/OPS_Clang  -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    - make
    - make install
# Stage "test"
# run-test:
#   stage: test
#   dependencies: [run-build]
#   script:


# Stage "docs"
# run-docs:
#   stage: docs
#   when: always
#   script:
    # - cd doc && make all clean
  # artifacts:
  #   expire_in: 1 week
  #   paths:
  #     - doc/user.pdf
  #     - doc/ops/html
  #     - doc/ops_translator/html

# Stage "clean"
# run-clean:
#   stage: clean
#   when: always
#   script:
    # - test-ops clean `git rev-parse HEAD`
    # - cd doc && make distclean