# Defines stages which are to be executed
image: registry.gitlab.com/op-dsl-ci/ops-ci
stages:
  - build
  - test
  - docs
  - clean

# Stage "build"
run-build:
  stage: build
  script:
    - cmake --version


# Stage "test"
run-test:
  stage: test
  dependencies: [run-build]
  script:


# Stage "docs"
run-docs:
  stage: docs
  when: always
  script:
    # - cd doc && make all clean
  # artifacts:
  #   expire_in: 1 week
  #   paths:
  #     - doc/user.pdf
  #     - doc/ops/html
  #     - doc/ops_translator/html

# Stage "clean"
run-clean:
  stage: clean
  when: always
  script:
    # - test-ops clean `git rev-parse HEAD`
    # - cd doc && make distclean
